version: "3.8"

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    restart: always

  pgadmin:
    image: dpage/pgadmin4:4.28
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

  redis:
    image: redis:6.0.9-buster
    ports:
      - "6379:6379"
      - "16379:16379"

  redisinsight:
    image: redislabs/redisinsight:1.8.0
    ports:
      - "8001:8001"
